### ISSUE TITLE
metrics API not working

### ISSUE THREAD

**Issue by anju-infracloud** [nikhilupadhyay1709/url-shortener-service#1]
Hey @nikhilupadhyay1709 , we shortened some URLs and then tried the metrics API which doesn't seem to work.

Can you please help us here if we're missing anything?

![image](https://github.com/nikhilupadhyay1709/url-shortener-service/assets/64465822/f4150b55-6af4-4732-acc9-0ecb4fb498ec)

**Comment by nikhilupadhyay1709** [comment]
Yea sure...
Let me provide you to curl of all the APIs..
Nikhil Upadhyay

**Comment by nikhilupadhyay1709** [comment]
curl -X POST http://localhost:8080/shorten -H "Content-Type: application/json" -d '{"url": "https://www.google.com"}'
curl -X GET http://localhost:8080/{shortURL}
curl -X GET http://localhost:8080/metrics

Remember the data is in only memory:
api endpoints: /metrics: 
{
    "top_domains": [
        "www.yahoo.com",
        "www.google.com"
    ]
}

note: shortURL is the response  form the POST method:
![Uploading Screenshot 2024-06-18 at 3.13.59 PM.png…]()

**Comment by nikhilupadhyay1709** [comment]
let me know still you are facing issue

**Comment by nikhilupadhyay1709** [comment]
<img width="1058" alt="Screenshot 2024-06-18 at 3 13 59 PM" src="https://github.com/nikhilupadhyay1709/url-shortener-service/assets/80529715/1158d9d2-ffe3-4d36-9f92-3fc4bd4cb997">

**Comment by anju-infracloud** [comment]
Yes we're still facing the same issue:

![image](https://github.com/nikhilupadhyay1709/url-shortener-service/assets/64465822/161bbcff-fd8e-4505-89b8-25b662b7899c)

**Comment by nikhilupadhyay1709** [comment]
> Yes we're still facing the same issue:
> 
> ![image](https://private-user-images.githubusercontent.com/64465822/340639710-161bbcff-fd8e-4505-89b8-25b662b7899c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDY2MzgsIm5iZiI6MTcxODcwNjMzOCwicGF0aCI6Ii82NDQ2NTgyMi8zNDA2Mzk3MTAtMTYxYmJjZmYtZmQ4ZS00NTA1LTg5YjgtMjViNjYyYjc4OTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEwMjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2Yjk3MzVhMTI2NzNjMGI1OTUxNDBiMDRiMmMwMjc4MjU4NTlkODY3NzdjZDYzMjg2MTc0NGU5NDhhOWUyNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5PVZ5Afr1ySSLvkOdVOdluCpSn_WLxXbtWR7Xo_42ro)

Is this docker image code ???

**Comment by nikhilupadhyay1709** [comment]
Because it is working on my end, if you see the image there, I have the same URL.

**Comment by anju-infracloud** [comment]
This is after running the code on the host with `go run main.go`

**Comment by nikhilupadhyay1709** [comment]
> This is after running the code on the host with `go run main.go`

should not happen because, in the same manner, I have tried and it is working.

Let us talk about it on a call where I will show you at my end.
or if you have any other ideas, let me know.

Thanks

**Comment by anju-infracloud** [comment]
I would look at URLs that are different in our examples

**Comment by nikhilupadhyay1709** [comment]
> I would look at URLs that are different in our examples

Sure. Thanks.

**Comment by anju-infracloud** [comment]
Hey @nikhilupadhyay1709 Were you able to find the problem?

**Comment by nikhilupadhyay1709** [comment]
Hi,

I did not find any problem at my end .
Are you still facing the issue...

Please check with the postman once or hit urls with the provided curls.

Thanks
Nikhil Upadhyay

**Comment by nikhilupadhyay1709** [comment]
Hi,

Is the issue resolved???
Nikhil Upadhyay

**Comment by nikhilupadhyay1709** [comment]
Hi,
Is the issue fixed??
Nikhil Upadhyay

**Comment by nikhilupadhyay1709** [comment]
@anju-infracloud Please check with the postman and if still facing issues drop screenshot here.

**Comment by nikhilupadhyay1709** [comment]
@anju-infracloud 
If you look at the image, it is fetching the domain data in the response of the metric API. There is no change in the code. Please confirm at your side
Thanks

<img width="1166" alt="Screenshot 2024-06-20 at 8 08 05 PM" src="https://github.com/nikhilupadhyay1709/url-shortener-service/assets/80529715/39513546-9002-455a-bf1c-2ea86d258fd8">

**Comment by nikhilupadhyay1709** [comment]
Hi @anju-infracloud have you looked at screenshot that I have provided yesterday???.
Please provide your feedback to HR team.
