### ISSUE TITLE
metrics for non http/https URLs don't seem to work

### ISSUE THREAD

**Issue by anju-infracloud** [nikhilupadhyay1709/url-shortener-service#2]
Hey @nikhilupadhyay1709 , with the latest fix we see the below problem

![image](https://github.com/nikhilupadhyay1709/url-shortener-service/assets/64465822/768073da-3828-4d63-ae60-0f985a2be00a)

**Comment by nikhilupadhyay1709** [comment]
> Hey @nikhilupadhyay1709 , with the latest fix we see the below problem
> 
> ![image](https://private-user-images.githubusercontent.com/64465822/342323445-768073da-3828-4d63-ae60-0f985a2be00a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjk3ODEsIm5iZiI6MTcxOTIyOTQ4MSwicGF0aCI6Ii82NDQ2NTgyMi8zNDIzMjM0NDUtNzY4MDczZGEtMzgyOC00ZDYzLWFlNjAtMGY5ODVhMmJlMDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDExNDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNmQ5MGI0NjM3YzBmNzJkOWZkOGI1NTVlNTA1NDdjOWFlYmEyY2RmN2Y5MzE3NTg3NTZjMmZlMjBlZmNiOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KQ058C0b8XrSoFQ3oG4yasr7feN93dPhskF97uD6GY4)

Sure let me fix that...

**Comment by nikhilupadhyay1709** [comment]
@anju-infracloud  I have pushed the updated code. Please let me know if you are still facing the issue.

**Comment by nikhilupadhyay1709** [comment]
@anju-infracloud  have fixed the issue last evening it self, Please check one more time.
Thanks

**Comment by nikhilupadhyay1709** [comment]
@anju-infracloud hi, any update on the lastest change???

**Comment by nikhilupadhyay1709** [comment]
@anju-infracloud any feedback from you ??
